--
-- Script was generated by Devart dbForge Studio for MySQL, Version 9.2.105.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 29/10/2025 14:36:17
-- Server version: 8.0.33
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE crmbeta;

--
-- Drop procedure `sp_actividades_crear`
--
DROP PROCEDURE IF EXISTS sp_actividades_crear;

--
-- Drop procedure `sp_actividades_listar_por_cliente`
--
DROP PROCEDURE IF EXISTS sp_actividades_listar_por_cliente;

--
-- Drop procedure `sp_dashboard_estadisticas`
--
DROP PROCEDURE IF EXISTS sp_dashboard_estadisticas;

--
-- Drop table `actividades`
--
DROP TABLE IF EXISTS actividades;

--
-- Drop procedure `sp_usuarios_actualizar`
--
DROP PROCEDURE IF EXISTS sp_usuarios_actualizar;

--
-- Drop procedure `sp_usuarios_crear`
--
DROP PROCEDURE IF EXISTS sp_usuarios_crear;

--
-- Drop procedure `sp_usuarios_eliminar`
--
DROP PROCEDURE IF EXISTS sp_usuarios_eliminar;

--
-- Drop procedure `sp_usuarios_listar`
--
DROP PROCEDURE IF EXISTS sp_usuarios_listar;

--
-- Drop procedure `sp_usuarios_login`
--
DROP PROCEDURE IF EXISTS sp_usuarios_login;

--
-- Drop procedure `sp_usuarios_obtener`
--
DROP PROCEDURE IF EXISTS sp_usuarios_obtener;

--
-- Drop table `usuarios`
--
DROP TABLE IF EXISTS usuarios;

--
-- Drop procedure `sp_perfiles_actualizar`
--
DROP PROCEDURE IF EXISTS sp_perfiles_actualizar;

--
-- Drop procedure `sp_perfiles_crear`
--
DROP PROCEDURE IF EXISTS sp_perfiles_crear;

--
-- Drop procedure `sp_perfiles_eliminar`
--
DROP PROCEDURE IF EXISTS sp_perfiles_eliminar;

--
-- Drop procedure `sp_perfiles_listar`
--
DROP PROCEDURE IF EXISTS sp_perfiles_listar;

--
-- Drop procedure `sp_perfiles_obtener`
--
DROP PROCEDURE IF EXISTS sp_perfiles_obtener;

--
-- Drop table `perfiles`
--
DROP TABLE IF EXISTS perfiles;

--
-- Drop procedure `sp_contactos_actualizar`
--
DROP PROCEDURE IF EXISTS sp_contactos_actualizar;

--
-- Drop procedure `sp_contactos_crear`
--
DROP PROCEDURE IF EXISTS sp_contactos_crear;

--
-- Drop procedure `sp_contactos_eliminar`
--
DROP PROCEDURE IF EXISTS sp_contactos_eliminar;

--
-- Drop procedure `sp_contactos_listar_por_cliente`
--
DROP PROCEDURE IF EXISTS sp_contactos_listar_por_cliente;

--
-- Drop procedure `sp_contactos_obtener`
--
DROP PROCEDURE IF EXISTS sp_contactos_obtener;

--
-- Drop table `contactos`
--
DROP TABLE IF EXISTS contactos;

--
-- Drop procedure `sp_oportunidades_actualizar`
--
DROP PROCEDURE IF EXISTS sp_oportunidades_actualizar;

--
-- Drop procedure `sp_oportunidades_actualizar_etapa`
--
DROP PROCEDURE IF EXISTS sp_oportunidades_actualizar_etapa;

--
-- Drop procedure `sp_oportunidades_crear`
--
DROP PROCEDURE IF EXISTS sp_oportunidades_crear;

--
-- Drop procedure `sp_oportunidades_eliminar`
--
DROP PROCEDURE IF EXISTS sp_oportunidades_eliminar;

--
-- Drop procedure `sp_oportunidades_listar`
--
DROP PROCEDURE IF EXISTS sp_oportunidades_listar;

--
-- Drop procedure `sp_oportunidades_obtener`
--
DROP PROCEDURE IF EXISTS sp_oportunidades_obtener;

--
-- Drop table `oportunidades`
--
DROP TABLE IF EXISTS oportunidades;

--
-- Drop procedure `sp_clientes_actualizar`
--
DROP PROCEDURE IF EXISTS sp_clientes_actualizar;

--
-- Drop procedure `sp_clientes_crear`
--
DROP PROCEDURE IF EXISTS sp_clientes_crear;

--
-- Drop procedure `sp_clientes_eliminar`
--
DROP PROCEDURE IF EXISTS sp_clientes_eliminar;

--
-- Drop procedure `sp_clientes_listar`
--
DROP PROCEDURE IF EXISTS sp_clientes_listar;

--
-- Drop procedure `sp_clientes_obtener`
--
DROP PROCEDURE IF EXISTS sp_clientes_obtener;

--
-- Drop table `clientes`
--
DROP TABLE IF EXISTS clientes;

--
-- Drop procedure `sp_tipos_documento_actualizar`
--
DROP PROCEDURE IF EXISTS sp_tipos_documento_actualizar;

--
-- Drop procedure `sp_tipos_documento_crear`
--
DROP PROCEDURE IF EXISTS sp_tipos_documento_crear;

--
-- Drop procedure `sp_tipos_documento_eliminar`
--
DROP PROCEDURE IF EXISTS sp_tipos_documento_eliminar;

--
-- Drop procedure `sp_tipos_documento_listar`
--
DROP PROCEDURE IF EXISTS sp_tipos_documento_listar;

--
-- Drop procedure `sp_tipos_documento_obtener`
--
DROP PROCEDURE IF EXISTS sp_tipos_documento_obtener;

--
-- Drop table `tipos_documento_identidad`
--
DROP TABLE IF EXISTS tipos_documento_identidad;

--
-- Drop procedure `sp_ubigeos_actualizar`
--
DROP PROCEDURE IF EXISTS sp_ubigeos_actualizar;

--
-- Drop procedure `sp_ubigeos_crear`
--
DROP PROCEDURE IF EXISTS sp_ubigeos_crear;

--
-- Drop procedure `sp_ubigeos_eliminar`
--
DROP PROCEDURE IF EXISTS sp_ubigeos_eliminar;

--
-- Drop procedure `sp_ubigeos_listar`
--
DROP PROCEDURE IF EXISTS sp_ubigeos_listar;

--
-- Drop procedure `sp_ubigeos_obtener`
--
DROP PROCEDURE IF EXISTS sp_ubigeos_obtener;

--
-- Drop table `ubigeos`
--
DROP TABLE IF EXISTS ubigeos;

--
-- Set default database
--
USE crmbeta;

--
-- Create table `ubigeos`
--
CREATE TABLE ubigeos (
  id_ubigeo int NOT NULL AUTO_INCREMENT,
  departamento varchar(100) NOT NULL,
  provincia varchar(100) NOT NULL,
  distrito varchar(100) NOT NULL,
  estado int DEFAULT 1,
  PRIMARY KEY (id_ubigeo)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
ROW_FORMAT = DYNAMIC;

DELIMITER $$

--
-- Create procedure `sp_ubigeos_obtener`
--
CREATE
DEFINER = 'evento'@'%'
PROCEDURE sp_ubigeos_obtener (IN p_id_ubigeo int)
BEGIN
  SELECT
    *
  FROM ubigeos
  WHERE id_ubigeo = p_id_ubigeo;
END
$$

--
-- Create procedure `sp_ubigeos_listar`
--
CREATE
DEFINER = 'evento'@'%'
PROCEDURE sp_ubigeos_listar ()
BEGIN
  SELECT
    *
  FROM ubigeos
  WHERE estado = 1;
END
$$

--
-- Create procedure `sp_ubigeos_eliminar`
--
CREATE
DEFINER = 'evento'@'%'
PROCEDURE sp_ubigeos_eliminar (IN p_id_ubigeo int)
BEGIN
  UPDATE ubigeos
  SET estado = 0
  WHERE id_ubigeo = p_id_ubigeo;
END
$$

--
-- Create procedure `sp_ubigeos_crear`
--
CREATE
DEFINER = 'evento'@'%'
PROCEDURE sp_ubigeos_crear (IN p_departamento varchar(100), IN p_provincia varchar(100), IN p_distrito varchar(100))
BEGIN
  INSERT INTO ubigeos (departamento, provincia, distrito)
    VALUES (p_departamento, p_provincia, p_distrito);
END
$$

--
-- Create procedure `sp_ubigeos_actualizar`
--
CREATE
DEFINER = 'evento'@'%'
PROCEDURE sp_ubigeos_actualizar (IN p_id_ubigeo int, IN p_departamento varchar(100), IN p_provincia varchar(100), IN p_distrito varchar(100))
BEGIN
  UPDATE ubigeos
  SET departamento = p_departamento,
      provincia = p_provincia,
      distrito = p_distrito
  WHERE id_ubigeo = p_id_ubigeo;
END
$$

DELIMITER ;

--
-- Create table `tipos_documento_identidad`
--
CREATE TABLE tipos_documento_identidad (
  id_tipo_documento int NOT NULL AUTO_INCREMENT,
  nombre_documento varchar(50) NOT NULL,
  estado int DEFAULT 1,
  PRIMARY KEY (id_tipo_documento)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
ROW_FORMAT = DYNAMIC;

DELIMITER $$

--
-- Create procedure `sp_tipos_documento_obtener`
--
CREATE
DEFINER = 'evento'@'%'
PROCEDURE sp_tipos_documento_obtener (IN p_id_tipo_documento int)
BEGIN
  SELECT
    *
  FROM tipos_documento_identidad
  WHERE id_tipo_documento = p_id_tipo_documento;
END
$$

--
-- Create procedure `sp_tipos_documento_listar`
--
CREATE
DEFINER = 'evento'@'%'
PROCEDURE sp_tipos_documento_listar ()
BEGIN
  SELECT
    *
  FROM tipos_documento_identidad
  WHERE estado = 1;
END
$$

--
-- Create procedure `sp_tipos_documento_eliminar`
--
CREATE
DEFINER = 'evento'@'%'
PROCEDURE sp_tipos_documento_eliminar (IN p_id_tipo_documento int)
BEGIN
  UPDATE tipos_documento_identidad
  SET estado = 0
  WHERE id_tipo_documento = p_id_tipo_documento;
END
$$

--
-- Create procedure `sp_tipos_documento_crear`
--
CREATE
DEFINER = 'evento'@'%'
PROCEDURE sp_tipos_documento_crear (IN p_nombre_documento varchar(50))
BEGIN
  INSERT INTO tipos_documento_identidad (nombre_documento)
    VALUES (p_nombre_documento);
END
$$

--
-- Create procedure `sp_tipos_documento_actualizar`
--
CREATE
DEFINER = 'evento'@'%'
PROCEDURE sp_tipos_documento_actualizar (IN p_id_tipo_documento int, IN p_nombre_documento varchar(50))
BEGIN
  UPDATE tipos_documento_identidad
  SET nombre_documento = p_nombre_documento
  WHERE id_tipo_documento = p_id_tipo_documento;
END
$$

DELIMITER ;

--
-- Create table `clientes`
--
CREATE TABLE clientes (
  id_cliente int NOT NULL AUTO_INCREMENT,
  nombre_cliente varchar(100) NOT NULL,
  direccion_cliente varchar(255) DEFAULT NULL,
  telefono_cliente varchar(20) DEFAULT NULL,
  website_cliente varchar(100) DEFAULT NULL,
  fecha_creacion datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  estado tinyint(1) NOT NULL DEFAULT 1,
  id_tipo_documento int DEFAULT NULL,
  numero_documento varchar(20) DEFAULT NULL,
  id_ubigeo int DEFAULT NULL,
  correo_electronico varchar(100) DEFAULT NULL,
  observaciones text DEFAULT NULL,
  PRIMARY KEY (id_cliente)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE clientes
ADD CONSTRAINT clientes_ibfk_1 FOREIGN KEY (id_tipo_documento)
REFERENCES tipos_documento_identidad (id_tipo_documento);

--
-- Create foreign key
--
ALTER TABLE clientes
ADD CONSTRAINT clientes_ibfk_2 FOREIGN KEY (id_ubigeo)
REFERENCES ubigeos (id_ubigeo);

DELIMITER $$

--
-- Create procedure `sp_clientes_obtener`
--
CREATE
DEFINER = 'evento'@'%'
PROCEDURE sp_clientes_obtener (IN `in_id_cliente` int)
BEGIN
  SELECT
    c.*,
    u.departamento,
    u.provincia,
    u.distrito
  FROM clientes c
    LEFT JOIN ubigeos u
      ON c.id_ubigeo = u.id_ubigeo
  WHERE c.id_cliente = in_id_cliente;
END
$$

--
-- Create procedure `sp_clientes_listar`
--
CREATE
DEFINER = 'evento'@'%'
PROCEDURE sp_clientes_listar ()
BEGIN
  SELECT
    c.id_cliente,
    c.nombre_cliente,
    c.telefono_cliente,
    c.website_cliente,
    td.nombre_documento,
    c.numero_documento,
    CONCAT(u.departamento, ', ', u.provincia, ', ', u.distrito) AS ubigeo,
    c.correo_electronico,
    c.direccion_cliente
  FROM clientes c
    LEFT JOIN tipos_documento_identidad td
      ON c.id_tipo_documento = td.id_tipo_documento
    LEFT JOIN ubigeos u
      ON c.id_ubigeo = u.id_ubigeo
  WHERE c.estado = 1;
END
$$

--
-- Create procedure `sp_clientes_eliminar`
--
CREATE
DEFINER = 'evento'@'%'
PROCEDURE sp_clientes_eliminar (IN `in_id_cliente` int)
BEGIN
  UPDATE clientes
  SET estado = 0
  WHERE id_cliente = in_id_cliente;
END
$$

--
-- Create procedure `sp_clientes_crear`
--
CREATE
DEFINER = 'evento'@'%'
PROCEDURE sp_clientes_crear (IN p_nombre_cliente varchar(255),
IN p_direccion_cliente varchar(255),
IN p_telefono_cliente varchar(20),
IN p_website_cliente varchar(100),
IN p_id_tipo_documento int,
IN p_numero_documento varchar(20),
IN p_id_ubigeo int,
IN p_correo_electronico varchar(100),
IN p_observaciones text)
BEGIN
  INSERT INTO clientes (nombre_cliente, direccion_cliente, telefono_cliente, website_cliente, id_tipo_documento, numero_documento, id_ubigeo, correo_electronico, observaciones)
    VALUES (p_nombre_cliente, p_direccion_cliente, p_telefono_cliente, p_website_cliente, p_id_tipo_documento, p_numero_documento, p_id_ubigeo, p_correo_electronico, p_observaciones);
END
$$

--
-- Create procedure `sp_clientes_actualizar`
--
CREATE
DEFINER = 'evento'@'%'
PROCEDURE sp_clientes_actualizar (IN p_id_cliente int,
IN p_nombre_cliente varchar(255),
IN p_direccion_cliente varchar(255),
IN p_telefono_cliente varchar(20),
IN p_website_cliente varchar(100),
IN p_id_tipo_documento int,
IN p_numero_documento varchar(20),
IN p_id_ubigeo int,
IN p_correo_electronico varchar(100),
IN p_observaciones text)
BEGIN
  UPDATE clientes
  SET nombre_cliente = p_nombre_cliente,
      direccion_cliente = p_direccion_cliente,
      telefono_cliente = p_telefono_cliente,
      website_cliente = p_website_cliente,
      id_tipo_documento = p_id_tipo_documento,
      numero_documento = p_numero_documento,
      id_ubigeo = p_id_ubigeo,
      correo_electronico = p_correo_electronico,
      observaciones = p_observaciones
  WHERE id_cliente = p_id_cliente;
END
$$

DELIMITER ;

--
-- Create table `oportunidades`
--
CREATE TABLE oportunidades (
  id_oportunidad int NOT NULL AUTO_INCREMENT,
  id_cliente int NOT NULL,
  nombre_oportunidad varchar(100) NOT NULL,
  valor_estimado decimal(10, 2) DEFAULT NULL,
  fecha_cierre date DEFAULT NULL,
  etapa enum ('Calificación', 'Propuesta', 'Negociación', 'Ganada', 'Perdida') NOT NULL DEFAULT 'Calificación',
  fecha_creacion datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  estado tinyint(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (id_oportunidad)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE oportunidades
ADD CONSTRAINT oportunidades_ibfk_1 FOREIGN KEY (id_cliente)
REFERENCES clientes (id_cliente) ON DELETE CASCADE ON UPDATE CASCADE;

DELIMITER $$

--
-- Create procedure `sp_oportunidades_obtener`
--
CREATE
DEFINER = 'evento'@'%'
PROCEDURE sp_oportunidades_obtener (IN `in_id_oportunidad` int)
BEGIN
  SELECT
    *
  FROM oportunidades
  WHERE id_oportunidad = in_id_oportunidad;
END
$$

--
-- Create procedure `sp_oportunidades_listar`
--
CREATE
DEFINER = 'evento'@'%'
PROCEDURE sp_oportunidades_listar ()
BEGIN
  SELECT
    o.*,
    c.nombre_cliente
  FROM oportunidades o
    INNER JOIN clientes c
      ON o.id_cliente = c.id_cliente
  WHERE o.estado = 1
  ORDER BY o.fecha_creacion DESC;
END
$$

--
-- Create procedure `sp_oportunidades_eliminar`
--
CREATE
DEFINER = 'evento'@'%'
PROCEDURE sp_oportunidades_eliminar (IN `in_id_oportunidad` int)
BEGIN
  UPDATE oportunidades
  SET estado = 0
  WHERE id_oportunidad = in_id_oportunidad;
END
$$

--
-- Create procedure `sp_oportunidades_crear`
--
CREATE
DEFINER = 'evento'@'%'
PROCEDURE sp_oportunidades_crear (IN `in_id_cliente` int,
IN `in_nombre_oportunidad` varchar(100),
IN `in_valor_estimado` decimal(10, 2),
IN `in_fecha_cierre` date,
IN `in_etapa` varchar(20))
BEGIN
  INSERT INTO oportunidades (id_cliente, nombre_oportunidad, valor_estimado, fecha_cierre, etapa)
    VALUES (in_id_cliente, in_nombre_oportunidad, in_valor_estimado, in_fecha_cierre, in_etapa);
END
$$

--
-- Create procedure `sp_oportunidades_actualizar_etapa`
--
CREATE
DEFINER = 'evento'@'%'
PROCEDURE sp_oportunidades_actualizar_etapa (IN `in_id_oportunidad` int,
IN `in_etapa` varchar(20))
BEGIN
  UPDATE oportunidades
  SET etapa = in_etapa
  WHERE id_oportunidad = in_id_oportunidad;
END
$$

--
-- Create procedure `sp_oportunidades_actualizar`
--
CREATE
DEFINER = 'evento'@'%'
PROCEDURE sp_oportunidades_actualizar (IN `in_id_oportunidad` int,
IN `in_id_cliente` int,
IN `in_nombre_oportunidad` varchar(100),
IN `in_valor_estimado` decimal(10, 2),
IN `in_fecha_cierre` date,
IN `in_etapa` varchar(20))
BEGIN
  UPDATE oportunidades
  SET id_cliente = in_id_cliente,
      nombre_oportunidad = in_nombre_oportunidad,
      valor_estimado = in_valor_estimado,
      fecha_cierre = in_fecha_cierre,
      etapa = in_etapa
  WHERE id_oportunidad = in_id_oportunidad;
END
$$

DELIMITER ;

--
-- Create table `contactos`
--
CREATE TABLE contactos (
  id_contacto int NOT NULL AUTO_INCREMENT,
  id_cliente int NOT NULL,
  nombre_contacto varchar(100) NOT NULL,
  cargo_contacto varchar(100) DEFAULT NULL,
  correo_contacto varchar(100) DEFAULT NULL,
  telefono_contacto varchar(20) DEFAULT NULL,
  fecha_creacion datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  estado tinyint(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (id_contacto)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE contactos
ADD CONSTRAINT contactos_ibfk_1 FOREIGN KEY (id_cliente)
REFERENCES clientes (id_cliente) ON DELETE CASCADE ON UPDATE CASCADE;

DELIMITER $$

--
-- Create procedure `sp_contactos_obtener`
--
CREATE
DEFINER = 'evento'@'%'
PROCEDURE sp_contactos_obtener (IN `in_id_contacto` int)
BEGIN
  SELECT
    *
  FROM contactos
  WHERE id_contacto = in_id_contacto;
END
$$

--
-- Create procedure `sp_contactos_listar_por_cliente`
--
CREATE
DEFINER = 'evento'@'%'
PROCEDURE sp_contactos_listar_por_cliente (IN `in_id_cliente` int)
BEGIN
  SELECT
    *
  FROM contactos
  WHERE id_cliente = in_id_cliente
  AND estado = 1
  ORDER BY nombre_contacto ASC;
END
$$

--
-- Create procedure `sp_contactos_eliminar`
--
CREATE
DEFINER = 'evento'@'%'
PROCEDURE sp_contactos_eliminar (IN `in_id_contacto` int)
BEGIN
  UPDATE contactos
  SET estado = 0
  WHERE id_contacto = in_id_contacto;
END
$$

--
-- Create procedure `sp_contactos_crear`
--
CREATE
DEFINER = 'evento'@'%'
PROCEDURE sp_contactos_crear (IN `in_id_cliente` int,
IN `in_nombre_contacto` varchar(100),
IN `in_cargo_contacto` varchar(100),
IN `in_correo_contacto` varchar(100),
IN `in_telefono_contacto` varchar(20))
BEGIN
  INSERT INTO contactos (id_cliente, nombre_contacto, cargo_contacto, correo_contacto, telefono_contacto)
    VALUES (in_id_cliente, in_nombre_contacto, in_cargo_contacto, in_correo_contacto, in_telefono_contacto);
END
$$

--
-- Create procedure `sp_contactos_actualizar`
--
CREATE
DEFINER = 'evento'@'%'
PROCEDURE sp_contactos_actualizar (IN `in_id_contacto` int,
IN `in_nombre_contacto` varchar(100),
IN `in_cargo_contacto` varchar(100),
IN `in_correo_contacto` varchar(100),
IN `in_telefono_contacto` varchar(20))
BEGIN
  UPDATE contactos
  SET nombre_contacto = in_nombre_contacto,
      cargo_contacto = in_cargo_contacto,
      correo_contacto = in_correo_contacto,
      telefono_contacto = in_telefono_contacto
  WHERE id_contacto = in_id_contacto;
END
$$

DELIMITER ;

--
-- Create table `perfiles`
--
CREATE TABLE perfiles (
  id_perfil int NOT NULL AUTO_INCREMENT,
  nombre_perfil varchar(50) NOT NULL,
  estado tinyint(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (id_perfil)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
ROW_FORMAT = DYNAMIC;

DELIMITER $$

--
-- Create procedure `sp_perfiles_obtener`
--
CREATE
DEFINER = 'evento'@'%'
PROCEDURE sp_perfiles_obtener (IN `in_id_perfil` int)
BEGIN
  SELECT
    *
  FROM perfiles
  WHERE id_perfil = in_id_perfil;
END
$$

--
-- Create procedure `sp_perfiles_listar`
--
CREATE
DEFINER = 'evento'@'%'
PROCEDURE sp_perfiles_listar ()
BEGIN
  SELECT
    *
  FROM perfiles;
END
$$

--
-- Create procedure `sp_perfiles_eliminar`
--
CREATE
DEFINER = 'evento'@'%'
PROCEDURE sp_perfiles_eliminar (IN `in_id_perfil` int)
BEGIN
  DELETE
    FROM perfiles
  WHERE id_perfil = in_id_perfil;
END
$$

--
-- Create procedure `sp_perfiles_crear`
--
CREATE
DEFINER = 'evento'@'%'
PROCEDURE sp_perfiles_crear (IN `in_nombre_perfil` varchar(50))
BEGIN
  INSERT INTO perfiles (nombre_perfil)
    VALUES (in_nombre_perfil);
END
$$

--
-- Create procedure `sp_perfiles_actualizar`
--
CREATE
DEFINER = 'evento'@'%'
PROCEDURE sp_perfiles_actualizar (IN `in_id_perfil` int, IN `in_nombre_perfil` varchar(50))
BEGIN
  UPDATE perfiles
  SET nombre_perfil = in_nombre_perfil
  WHERE id_perfil = in_id_perfil;
END
$$

DELIMITER ;

--
-- Create table `usuarios`
--
CREATE TABLE usuarios (
  id_usuario int NOT NULL AUTO_INCREMENT,
  nombre_usuario varchar(50) NOT NULL,
  apellido_usuario varchar(50) NOT NULL,
  correo_usuario varchar(100) NOT NULL,
  clave_usuario varchar(255) NOT NULL,
  id_perfil int NOT NULL,
  estado tinyint(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (id_usuario)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE usuarios
ADD CONSTRAINT usuarios_ibfk_1 FOREIGN KEY (id_perfil)
REFERENCES perfiles (id_perfil) ON DELETE CASCADE ON UPDATE CASCADE;

DELIMITER $$

--
-- Create procedure `sp_usuarios_obtener`
--
CREATE
DEFINER = 'evento'@'%'
PROCEDURE sp_usuarios_obtener (IN `in_id_usuario` int)
BEGIN
  SELECT
    *
  FROM usuarios
  WHERE id_usuario = in_id_usuario;
END
$$

--
-- Create procedure `sp_usuarios_login`
--
CREATE
DEFINER = 'evento'@'%'
PROCEDURE sp_usuarios_login (IN `in_correo_usuario` varchar(100))
BEGIN
  SELECT
    *
  FROM usuarios
  WHERE correo_usuario COLLATE utf8mb4_general_ci
  = in_correo_usuario COLLATE utf8mb4_general_ci;
END
$$

--
-- Create procedure `sp_usuarios_listar`
--
CREATE
DEFINER = 'evento'@'%'
PROCEDURE sp_usuarios_listar ()
BEGIN
  SELECT
    u.*,
    p.nombre_perfil
  FROM usuarios u
    INNER JOIN perfiles p
      ON u.id_perfil = p.id_perfil;
END
$$

--
-- Create procedure `sp_usuarios_eliminar`
--
CREATE
DEFINER = 'evento'@'%'
PROCEDURE sp_usuarios_eliminar (IN `in_id_usuario` int)
BEGIN
  DELETE
    FROM usuarios
  WHERE id_usuario = in_id_usuario;
END
$$

--
-- Create procedure `sp_usuarios_crear`
--
CREATE
DEFINER = 'evento'@'%'
PROCEDURE sp_usuarios_crear (IN `in_nombre_usuario` varchar(50), IN `in_apellido_usuario` varchar(50), IN `in_correo_usuario` varchar(100), IN `in_clave_usuario` varchar(255), IN `in_id_perfil` int)
BEGIN
  INSERT INTO usuarios (nombre_usuario, apellido_usuario, correo_usuario, clave_usuario, id_perfil)
    VALUES (in_nombre_usuario, in_apellido_usuario, in_correo_usuario, in_clave_usuario, in_id_perfil);
END
$$

--
-- Create procedure `sp_usuarios_actualizar`
--
CREATE
DEFINER = 'evento'@'%'
PROCEDURE sp_usuarios_actualizar (IN `in_id_usuario` int, IN `in_nombre_usuario` varchar(50), IN `in_apellido_usuario` varchar(50), IN `in_correo_usuario` varchar(100), IN `in_clave_usuario` varchar(255), IN `in_id_perfil` int)
BEGIN
  UPDATE usuarios
  SET nombre_usuario = in_nombre_usuario,
      apellido_usuario = in_apellido_usuario,
      correo_usuario = in_correo_usuario,
      clave_usuario = in_clave_usuario,
      id_perfil = in_id_perfil
  WHERE id_usuario = in_id_usuario;
END
$$

DELIMITER ;

--
-- Create table `actividades`
--
CREATE TABLE actividades (
  id_actividad int NOT NULL AUTO_INCREMENT,
  id_cliente int DEFAULT NULL,
  id_contacto int DEFAULT NULL,
  id_oportunidad int DEFAULT NULL,
  id_usuario int NOT NULL,
  tipo_actividad enum ('Llamada', 'Reunión', 'Correo', 'Tarea') NOT NULL,
  asunto varchar(255) NOT NULL,
  descripcion text DEFAULT NULL,
  fecha_actividad datetime NOT NULL,
  fecha_creacion datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id_actividad)
)
ENGINE = INNODB,
AUTO_INCREMENT = 9,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE actividades
ADD CONSTRAINT actividades_ibfk_1 FOREIGN KEY (id_cliente)
REFERENCES clientes (id_cliente) ON DELETE SET NULL;

--
-- Create foreign key
--
ALTER TABLE actividades
ADD CONSTRAINT actividades_ibfk_2 FOREIGN KEY (id_contacto)
REFERENCES contactos (id_contacto) ON DELETE SET NULL;

--
-- Create foreign key
--
ALTER TABLE actividades
ADD CONSTRAINT actividades_ibfk_3 FOREIGN KEY (id_oportunidad)
REFERENCES oportunidades (id_oportunidad) ON DELETE SET NULL;

--
-- Create foreign key
--
ALTER TABLE actividades
ADD CONSTRAINT actividades_ibfk_4 FOREIGN KEY (id_usuario)
REFERENCES usuarios (id_usuario) ON DELETE CASCADE;

DELIMITER $$

--
-- Create procedure `sp_dashboard_estadisticas`
--
CREATE
DEFINER = 'evento'@'%'
PROCEDURE sp_dashboard_estadisticas ()
BEGIN
  SELECT
    (SELECT
        COUNT(*)
      FROM clientes
      WHERE estado = 1) AS total_clientes,
    (SELECT
        COUNT(*)
      FROM oportunidades
      WHERE estado = 1
      AND etapa NOT IN ('Ganada', 'Perdida')) AS oportunidades_activas,
    (SELECT
        COUNT(*)
      FROM actividades
      WHERE fecha_actividad >= CURDATE()) AS actividades_pendientes;
END
$$

--
-- Create procedure `sp_actividades_listar_por_cliente`
--
CREATE
DEFINER = 'evento'@'%'
PROCEDURE sp_actividades_listar_por_cliente (IN `in_id_cliente` int)
BEGIN
  SELECT
    a.*,
    u.nombre_usuario
  FROM actividades a
    INNER JOIN usuarios u
      ON a.id_usuario = u.id_usuario
  WHERE a.id_cliente = in_id_cliente
  ORDER BY a.fecha_actividad DESC;
END
$$

--
-- Create procedure `sp_actividades_crear`
--
CREATE
DEFINER = 'evento'@'%'
PROCEDURE sp_actividades_crear (IN `in_id_cliente` int,
IN `in_id_contacto` int,
IN `in_id_oportunidad` int,
IN `in_id_usuario` int,
IN `in_tipo_actividad` varchar(20),
IN `in_asunto` varchar(255),
IN `in_descripcion` text,
IN `in_fecha_actividad` datetime)
BEGIN
  DECLARE v_id_oportunidad int;

  -- Si el parámetro llega NULL o 0, calculamos el siguiente número
  IF in_id_oportunidad IS NULL
    OR in_id_oportunidad = 0 THEN
    SELECT
      IFNULL(MAX(id_oportunidad), 0) + 1 INTO v_id_oportunidad
    FROM actividades;
  ELSE
    SET v_id_oportunidad = in_id_oportunidad;
  END IF;

  INSERT INTO actividades (id_cliente,
  id_contacto,
  id_oportunidad,
  id_usuario,
  tipo_actividad,
  asunto,
  descripcion,
  fecha_actividad)
    VALUES (in_id_cliente, in_id_contacto, v_id_oportunidad, in_id_usuario, in_tipo_actividad, in_asunto, in_descripcion, in_fecha_actividad);
END
$$

DELIMITER ;

-- 
-- Dumping data for table ubigeos
--
INSERT INTO ubigeos VALUES
(1, 'Lima', 'Lima', 'Lima', 1),
(2, 'd', 'd', 'd', 0);

-- 
-- Dumping data for table tipos_documento_identidad
--
INSERT INTO tipos_documento_identidad VALUES
(1, 'DNI', 1),
(2, 'RUC', 1),
(3, 'CARNET', 1),
(4, 'i', 0);

-- 
-- Dumping data for table perfiles
--
INSERT INTO perfiles VALUES
(1, 'Administrador', 1),
(2, 'Usuario', 1),
(3, 'VENDEDOR', 1);

-- 
-- Dumping data for table clientes
--
INSERT INTO clientes VALUES
(1, 'FALABELLA.COM S.A.C.', 'AV. PASEO DE LA REPUBLICA - Nro: 3220  - URBANIZACION SANTA ANA  - SAN ISIDRO', '123213213', '', '2025-10-28 14:21:59', 1, 2, '20547836473', 1, '', ''),
(2, 'PACLIFE SA', 'AV LARCO 930 OF 302 MIRAFLORES', '4471788', '', '2025-10-28 14:26:13', 1, NULL, NULL, NULL, NULL, NULL),
(3, 'MIGUEL', 'Av Jose larco 930', '4471788', '', '2025-10-28 15:40:13', 0, 1, '777777777777', 1, '', ''),
(4, 'ADVISOR GLOBAL SYSTEMS SOCIEDAD ANONIMA CERRADA', 'AV. LARCO - Nro: 930  - INT.: 302  - MIRAFLORES', '12345678', '', '2025-10-28 16:54:38', 1, 2, '20517585794', 1, 'sistemas@mgsa.com.pe', 'Holaa');

-- 
-- Dumping data for table usuarios
--
INSERT INTO usuarios VALUES
(1, 'Admin', 'User', 'admin@crm.com', '$2y$10$HoyyaTnauVkSCKsK8NOyDOkCsVPedppXAc7vVGs7F9LO2e1EgWIPC', 1, 1),
(2, 'Santiago', 'Prueba', 'santiago@crm.com', '$2y$10$XizLkd9gHRDLm6tDaGJZFeHkMoRIC9rlnH2RnjJqzWKLZB1djdtWG', 3, 1),
(4, 'sistemas', 'sistemas', 'sistemas@crm.com', '$2y$10$C9o2j5cOi1jNuHmgtCfvTex4AVpaeop4giGxYjrPKSRtgU601peJi', 1, 1);

-- 
-- Dumping data for table oportunidades
--
INSERT INTO oportunidades VALUES
(1, 1, 'SERVICIO DE SERVIDORES', 9999.00, '2025-10-28', 'Negociación', '2025-10-28 14:22:54', 1),
(2, 1, 'VENTA DE ADVISOR', 1111.00, '2025-10-30', 'Calificación', '2025-10-28 14:23:22', 1),
(3, 2, 'CONTRATO RENOVACION MENSUAL PACLIFE', 500.00, '2025-10-31', 'Propuesta', '2025-10-28 14:26:50', 0);

-- 
-- Dumping data for table contactos
--
INSERT INTO contactos VALUES
(1, 1, 'PRUEBA', '1', 'sistemas@mgsa.com.pe', '1', '2025-10-28 14:43:29', 0),
(2, 4, 'PRUEBA', 'VENDEDOR', 'prueba@mgsa.com.pe', '945123456', '2025-10-29 12:41:11', 1);

-- 
-- Dumping data for table actividades
--
INSERT INTO actividades VALUES
(7, 1, NULL, 1, 4, 'Reunión', 'DEMOSTRACION', 'demo', '2025-11-02 10:00:00', '2025-10-29 14:01:37'),
(8, 1, NULL, 2, 4, 'Llamada', 'SOPORTE', 'SOPORTE', '2025-11-03 13:00:00', '2025-10-29 14:02:18');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;